# -*- coding: utf-8 -*-
"""taller plan 4 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oov1BiMvPj6IkJtvC6ByH9H73wNBu-oS
"""

# ============================================================
# PLANEACION INCREMENTAL CON HORIZONTE MOVIL
# Programacion y Control de Produccion - Taller 4
#
# ============================================================

import numpy as np
import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.styles import (Font, PatternFill, Alignment,
                              Border, Side, GradientFill)
from openpyxl.utils import get_column_letter
from statsmodels.tsa.holtwinters import ExponentialSmoothing, SimpleExpSmoothing
import warnings
warnings.filterwarnings("ignore")

ARCHIVO_P1 = 'PRODUCTO 1 CON AJUSTE.xlsx'
ARCHIVO_P2 = 'PRODUCTO 2 CON AJUSTE.xlsx'


# ============================================================
# 1. CARGA DE DATOS
# ============================================================

def cargar_demanda(archivo, prefijo):
    try:
        wb = load_workbook(archivo, read_only=True)
    except FileNotFoundError:
        print(f"Error: No se encontro '{archivo}'.")
        exit()
    ws = wb["InformacionEntrada"]
    datos = {}
    for row in ws.iter_rows(max_row=10, values_only=True):
        if row and isinstance(row[0], str) and row[0] not in ('Centros', '|'):
            vals = [v for v in row[1:13] if isinstance(v, (int, float))]
            if len(vals) == 12:
                datos[f"{prefijo}_{row[0]}"] = vals
    return datos

demanda_historica = {}
demanda_historica.update(cargar_demanda(ARCHIVO_P1, 'P1'))
demanda_historica.update(cargar_demanda(ARCHIVO_P2, 'P2'))

NODOS = [
    'P1_PF1', 'P1_CD1', 'P1_CD2', 'P1_CD3',
    'P1_F1',  'P1_F2',  'P1_F3',  'P1_F4',
    'P2_PF1', 'P2_PF2', 'P2_CD_Norte', 'P2_CD_Sur',
    'P2_F_A', 'P2_F_B', 'P2_F_C', 'P2_F_D'
]

# Inventario al cierre de t12 extraido de las hojas con ajuste
IO_T12 = {
    'P1_PF1': 37,  'P1_CD1':  2,  'P1_CD2': 26,  'P1_CD3': 67,
    'P1_F1':  49,  'P1_F2':   9,  'P1_F3':  20,  'P1_F4':  21,
    'P2_PF1':  2,  'P2_PF2': 12,  'P2_CD_Norte': 64, 'P2_CD_Sur': 31,
    'P2_F_A': 71,  'P2_F_B': 86,  'P2_F_C': 39,  'P2_F_D': 42,
}

PARAMETROS = {
    'P1_PF1':      {'SS': 23,  'Q': 47,  'LT': 0},
    'P1_CD1':      {'SS': 23,  'Q': 69,  'LT': 1},
    'P1_CD2':      {'SS': 25,  'Q': 69,  'LT': 2},
    'P1_CD3':      {'SS': 19,  'Q': 70,  'LT': 2},
    'P1_F1':       {'SS': 30,  'Q': 51,  'LT': 2},
    'P1_F2':       {'SS': 26,  'Q': 66,  'LT': 2},
    'P1_F3':       {'SS': 24,  'Q': 56,  'LT': 2},
    'P1_F4':       {'SS': 25,  'Q': 39,  'LT': 2},
    'P2_PF1':      {'SS': 46,  'Q': 72,  'LT': 0},
    'P2_PF2':      {'SS': 37,  'Q': 143, 'LT': 0},
    'P2_CD_Norte': {'SS': 46,  'Q': 76,  'LT': 3},
    'P2_CD_Sur':   {'SS': 28,  'Q': 85,  'LT': 3},
    'P2_F_A':      {'SS': 34,  'Q': 72,  'LT': 3},
    'P2_F_B':      {'SS': 61,  'Q': 146, 'LT': 3},
    'P2_F_C':      {'SS': 22,  'Q': 148, 'LT': 1},
    'P2_F_D':      {'SS': 68,  'Q': 58,  'LT': 1},
}


# ============================================================
# 2. METODOS DE PRONOSTICO Y SELECCION
# ============================================================

def rmse(real, pred):
    return np.sqrt(np.mean(
        (np.array(real, dtype=float) - np.array(pred, dtype=float))**2
    ))

def _pm3(serie, h):
    base = np.mean(serie[-3:])
    return [max(0, round(base))] * h

def _ses(serie, h):
    m = SimpleExpSmoothing(serie).fit(optimized=True)
    return [max(0, round(v)) for v in m.forecast(h)]

def _holt(serie, h):
    m = ExponentialSmoothing(serie, trend='add').fit(optimized=True)
    return [max(0, round(v)) for v in m.forecast(h)]

def _hw(serie, h):
    m = ExponentialSmoothing(
        serie, trend='add', seasonal='add', seasonal_periods=3
    ).fit(optimized=True)
    return [max(0, round(v)) for v in m.forecast(h)]

METODOS = {'PM3': _pm3, 'SES': _ses, 'Holt': _holt, 'HW': _hw}

def seleccionar_metodo(serie):
    train, test = serie[:6], serie[6:]
    errores = {}
    for nombre, fn in METODOS.items():
        try:
            errores[nombre] = rmse(test, fn(train, len(test)))
        except Exception:
            errores[nombre] = float('inf')
    mejor = min(errores, key=errores.get)
    return mejor, errores


# ============================================================
# 3. HORIZONTE MOVIL
#
# Paso 1: ventana t3-t8  -> pronostico inicial (12 periodos)
#         validar t9-t12 contra real -> RMSE
# Paso 2: ventana t3-t12 -> pronostico corregido t13-t24
# ============================================================

def aplicar_horizonte_movil(serie, metodo):
    fn = METODOS[metodo]

    ventana_1   = serie[2:8]           # t3 a t8
    pron_ini    = fn(ventana_1, 12)    # t9 a t20
    real_t9_t12 = serie[8:12]
    rmse_val1   = rmse(real_t9_t12, pron_ini[:4])

    ventana_2   = serie[2:12]          # t3 a t12
    pron_final  = fn(ventana_2, 12)    # t13 a t24

    return {
        'ventana_1':    ventana_1,
        'pron_ini':     pron_ini,
        'rmse_val1':    round(rmse_val1, 2),
        'ventana_2':    ventana_2,
        'pron_final':   pron_final,
    }


# ============================================================
# 4. PLAN DE PRODUCCION PROYECTADO (PCO)
# ============================================================

def calcular_pco(demanda_pron, SS, Io, Q, LT):
    h   = len(demanda_pron)
    inv = [0.0] * (h + 1)
    inv[0] = Io
    PRO = [0] * h
    PCO = [0] * h
    RN  = [0] * h

    for t in range(h):
        inv_disp = inv[t] - demanda_pron[t]
        RN[t]    = max(0, SS - inv_disp)
        if RN[t] > 0:
            PRO[t] = int(np.ceil(RN[t] / Q)) * Q
        inv[t+1] = inv[t] + PRO[t] - demanda_pron[t]
        if t - LT >= 0:
            PCO[t - LT] = PRO[t]

    return PCO, PRO, [round(v, 1) for v in inv[1:]], RN


# ============================================================
# 5. EJECUTAR ANALISIS (todos o un nodo)
# ============================================================

def ejecutar_analisis(nodos=None, verbose=True):
    if nodos is None:
        nodos = NODOS

    resultados = {}
    for nombre in nodos:
        if nombre not in demanda_historica:
            continue

        serie           = demanda_historica[nombre]
        metodo, errores = seleccionar_metodo(serie)
        hm              = aplicar_horizonte_movil(serie, metodo)
        p               = PARAMETROS[nombre]
        PCO, PRO, INV, RN = calcular_pco(
            hm['pron_final'], p['SS'], IO_T12[nombre], p['Q'], p['LT']
        )

        resultados[nombre] = {
            'metodo':      metodo,
            'errores':     errores,
            'rmse_val1':   hm['rmse_val1'],
            'ventana_1':   hm['ventana_1'],
            'pron_ini':    hm['pron_ini'],
            'ventana_2':   hm['ventana_2'],
            'pron_final':  hm['pron_final'],
            'PCO': PCO, 'PRO': PRO, 'INV': INV, 'RN': RN,
        }

        if verbose:
            _imprimir_nodo(nombre, resultados[nombre])

    return resultados


def _imprimir_nodo(nombre, d):
    print(f"\n{'='*65}")
    print(f" NODO: {nombre}  |  Metodo: {d['metodo']}  |  RMSE val1: {d['rmse_val1']}")
    print(f"{'='*65}")
    print(f" Errores RMSE seleccion (train t1-t6, val t7-t12):")
    for m, e in d['errores'].items():
        marca = ' <--' if m == d['metodo'] else ''
        print(f"   {m:5s}: {e:.2f}{marca}")

    enc1 = ' '.join([f"t{i:02d}" for i in range(9, 21)])
    val1 = ' '.join([f"{v:4d}" for v in d['pron_ini']])
    print(f"\n Paso 1 - Ventana t3-t8, pronostico t9-t20:")
    print(f"   {enc1}")
    print(f"   {val1}")
    print(f"   RMSE vs real t9-t12: {d['rmse_val1']}")

    enc2 = ' '.join([f"t{i:02d}" for i in range(13, 25)])
    val2 = ' '.join([f"{v:4d}" for v in d['pron_final']])
    print(f"\n Paso 2 - Ventana t3-t12 corregida, pronostico t13-t24:")
    print(f"   {enc2}")
    print(f"   {val2}")

    valp = ' '.join([f"{v:4d}" for v in d['PCO']])
    print(f"\n PCO proyectado t13-t24:")
    print(f"   {enc2}")
    print(f"   {valp}")


# ============================================================
# 6. EXPORTAR A EXCEL  (mismo estilo del taller)
# ============================================================

# Paleta del taller
C_AZUL_OSC  = "1F4E79"   # encabezados principales
C_AZUL_MED  = "2E75B6"   # subencabezados
C_AZUL_CLAR = "BDD7EE"   # filas de etiqueta
C_VERDE     = "E2EFDA"   # filas con PCO > 0
C_GRIS      = "F2F2F2"   # filas alternas
C_AMARILLO  = "FFF2CC"   # RMSE / validacion
BLANCO      = "FFFFFF"

def _borde_fino():
    lado = Side(style='thin', color="BFBFBF")
    return Border(left=lado, right=lado, top=lado, bottom=lado)

def _borde_medio():
    lado = Side(style='medium', color="1F4E79")
    return Border(left=lado, right=lado, top=lado, bottom=lado)

def _hdr(ws, fila, col, valor, bg=C_AZUL_OSC, fg="FFFFFF", bold=True, center=True):
    c = ws.cell(fila, col, valor)
    c.font      = Font(name='Calibri', bold=bold, color=fg, size=10)
    c.fill      = PatternFill("solid", fgColor=bg)
    c.border    = _borde_fino()
    if center:
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    return c

def _cel(ws, fila, col, valor, bg=BLANCO, bold=False, center=True, color_fuente="000000"):
    c = ws.cell(fila, col, valor)
    c.font      = Font(name='Calibri', bold=bold, color=color_fuente, size=10)
    c.fill      = PatternFill("solid", fgColor=bg)
    c.border    = _borde_fino()
    if center:
        c.alignment = Alignment(horizontal="center", vertical="center")
    return c

def _titulo_seccion(ws, fila, col_ini, col_fin, texto):
    ws.merge_cells(start_row=fila, start_column=col_ini,
                   end_row=fila,   end_column=col_fin)
    c = ws.cell(fila, col_ini, texto)
    c.font      = Font(name='Calibri', bold=True, color=BLANCO, size=11)
    c.fill      = PatternFill("solid", fgColor=C_AZUL_MED)
    c.alignment = Alignment(horizontal="left", vertical="center", indent=1)
    c.border    = _borde_medio()

def exportar_excel(resultados):
    wb = Workbook()
    wb.remove(wb.active)

    semanas_hist = list(range(1, 13))
    semanas_fut  = list(range(13, 25))
    N_COLS       = 15   # columnas usadas en hojas de nodo

    # --------------------------------------------------
    # HOJA RESUMEN
    # --------------------------------------------------
    ws = wb.create_sheet("Resumen")
    ws.sheet_view.showGridLines = False
    ws.row_dimensions[1].height = 30
    ws.row_dimensions[2].height = 22

    # Titulo
    ws.merge_cells("A1:R1")
    c = ws.cell(1, 1, "Planeación Incremental con Horizonte Móvil — Resumen por Nodo")
    c.font      = Font(name='Calibri', bold=True, color=BLANCO, size=13)
    c.fill      = PatternFill("solid", fgColor=C_AZUL_OSC)
    c.alignment = Alignment(horizontal="center", vertical="center")

    hdrs = (["Nodo", "Método", "RMSE\nval1"] +
            [f"t{s}" for s in semanas_fut])
    for j, h in enumerate(hdrs, 1):
        _hdr(ws, 2, j, h)

    for i, (nombre, d) in enumerate(resultados.items(), 3):
        bg = C_GRIS if i % 2 == 0 else BLANCO
        _cel(ws, i, 1, nombre,         bg=bg, bold=True, center=False)
        _cel(ws, i, 2, d['metodo'],    bg=bg)
        c = _cel(ws, i, 3, d['rmse_val1'], bg=C_AMARILLO)
        for k, v in enumerate(d['pron_final'], 4):
            _cel(ws, i, k, v, bg=bg)

    anchos_res = [20, 8, 9] + [7]*12
    for j, w in enumerate(anchos_res, 1):
        ws.column_dimensions[get_column_letter(j)].width = w

    # --------------------------------------------------
    # HOJA POR NODO
    # --------------------------------------------------
    for nombre, d in resultados.items():
        ws = wb.create_sheet(nombre[:28])
        ws.sheet_view.showGridLines = False

        # Congelar primera columna
        ws.freeze_panes = "B1"

        # Ajuste de anchos
        ws.column_dimensions['A'].width = 28
        for j in range(2, N_COLS + 2):
            ws.column_dimensions[get_column_letter(j)].width = 8

        fila = 1

        # --- Titulo nodo ---
        ws.merge_cells(start_row=fila, start_column=1,
                       end_row=fila,   end_column=N_COLS)
        c = ws.cell(fila, 1, f"Nodo: {nombre}")
        c.font      = Font(name='Calibri', bold=True, color=BLANCO, size=13)
        c.fill      = PatternFill("solid", fgColor=C_AZUL_OSC)
        c.alignment = Alignment(horizontal="left", vertical="center", indent=1)
        ws.row_dimensions[fila].height = 28
        fila += 1

        # --- Seleccion de metodo ---
        _titulo_seccion(ws, fila, 1, N_COLS,
                        "1. Selección automática del método de pronóstico")
        fila += 1

        _hdr(ws, fila, 1, "Método",      bg=C_AZUL_CLAR, fg="000000")
        _hdr(ws, fila, 2, "RMSE (t7-t12)", bg=C_AZUL_CLAR, fg="000000")
        _hdr(ws, fila, 3, "Seleccionado", bg=C_AZUL_CLAR, fg="000000")
        fila += 1

        for m, e in d['errores'].items():
            selec = "SI" if m == d['metodo'] else ""
            bg_m  = C_AMARILLO if m == d['metodo'] else BLANCO
            _cel(ws, fila, 1, m,          bg=bg_m, bold=(m == d['metodo']))
            _cel(ws, fila, 2, round(e,2), bg=bg_m)
            _cel(ws, fila, 3, selec,      bg=bg_m, bold=True,
                 color_fuente=C_AZUL_OSC if selec else "000000")
            fila += 1

        fila += 1

        # --- Paso 1 ---
        _titulo_seccion(ws, fila, 1, N_COLS,
                        "2. Paso 1 — Ventana t3–t8: pronóstico inicial y validación")
        fila += 1

        # Encabezados semanas t3-t8
        _hdr(ws, fila, 1, "Demanda histórica t3-t8", bg=C_AZUL_CLAR, fg="000000")
        for j, s in enumerate(range(3, 9), 2):
            _hdr(ws, fila, j, f"t{s}", bg=C_AZUL_CLAR, fg="000000")
        fila += 1
        _cel(ws, fila, 1, "Valores", bold=False, center=False)
        for j, v in enumerate(d['ventana_1'], 2):
            _cel(ws, fila, j, v)
        fila += 1

        # Pronostico inicial t9-t20
        _hdr(ws, fila, 1, "Pronóstico inicial t9–t20", bg=C_AZUL_CLAR, fg="000000")
        for j, s in enumerate(range(9, 21), 2):
            _hdr(ws, fila, j, f"t{s}", bg=C_AZUL_CLAR, fg="000000")
        fila += 1
        _cel(ws, fila, 1, f"Método: {d['metodo']}", bold=True, center=False)
        for j, v in enumerate(d['pron_ini'], 2):
            _cel(ws, fila, j, v)
        fila += 1

        # RMSE validacion
        _cel(ws, fila, 1, "RMSE validación (pron t9-t12 vs real t9-t12)",
             bg=C_AMARILLO, bold=True, center=False)
        _cel(ws, fila, 2, d['rmse_val1'], bg=C_AMARILLO, bold=True)
        fila += 2

        # --- Paso 2 ---
        _titulo_seccion(ws, fila, 1, N_COLS,
                        "3. Paso 2 — Corrección: ventana t3–t12 → pronóstico t13–t24")
        fila += 1

        _hdr(ws, fila, 1, "Demanda histórica t3-t12", bg=C_AZUL_CLAR, fg="000000")
        for j, s in enumerate(range(3, 13), 2):
            _hdr(ws, fila, j, f"t{s}", bg=C_AZUL_CLAR, fg="000000")
        fila += 1
        _cel(ws, fila, 1, "Valores", bold=False, center=False)
        for j, v in enumerate(d['ventana_2'], 2):
            _cel(ws, fila, j, v)
        fila += 1

        _hdr(ws, fila, 1, "Pronóstico corregido t13–t24", bg=C_AZUL_CLAR, fg="000000")
        for j, s in enumerate(range(13, 25), 2):
            _hdr(ws, fila, j, f"t{s}", bg=C_AZUL_CLAR, fg="000000")
        fila += 1
        _cel(ws, fila, 1, f"Método: {d['metodo']}", bold=True, center=False)
        for j, v in enumerate(d['pron_final'], 2):
            _cel(ws, fila, j, v, bg=C_VERDE)
        fila += 2

        # --- PCO proyectado ---
        _titulo_seccion(ws, fila, 1, N_COLS,
                        "4. Plan de Producción Proyectado (t13–t24)")
        fila += 1

        hdrs_pco = ["Concepto"] + [f"t{s}" for s in semanas_fut]
        for j, h in enumerate(hdrs_pco, 1):
            _hdr(ws, fila, j, h)
        fila += 1

        filas_pco = [
            ("Requerimiento Bruto (RB)",  d['pron_final']),
            ("Requerimiento Neto (RN)",   d['RN']),
            ("Plan de Recibir (PRO)",     d['PRO']),
            ("Plan de Colocar (PCO)",     d['PCO']),
            ("Inventario proyectado",     d['INV']),
        ]
        for etiqueta, valores in filas_pco:
            es_pco = etiqueta.startswith("Plan de Colocar")
            bg_fila = C_VERDE if es_pco else BLANCO
            _cel(ws, fila, 1, etiqueta,
                 bg=bg_fila, bold=es_pco, center=False)
            for j, v in enumerate(valores, 2):
                bg_v = C_VERDE if (es_pco and v > 0) else bg_fila
                _cel(ws, fila, j, v, bg=bg_v, bold=(es_pco and v > 0))
            fila += 1

    # --------------------------------------------------
    # GUARDAR
    # --------------------------------------------------
    nombre_archivo = "Planeacion_Incremental_Resultados.xlsx"
    wb.save(nombre_archivo)
    print(f"\n  Archivo exportado: {nombre_archivo}")
    return nombre_archivo


# ============================================================
# 7. MENU
# ============================================================

def menu():
    while True:
        print(f"\n{'='*65}")
        print(f"  PLANEACION INCREMENTAL - HORIZONTE MOVIL")
        print(f"{'='*65}")
        print("  1. Analizar todos los nodos")
        print("  2. Analizar un nodo especifico")
        print("  3. Resumen comparativo de metodos")
        print("  4. Exportar resultados a Excel")
        print("  5. Salir")

        op = input("\nSeleccione una opcion: ").strip()

        if op == '1':
            ejecutar_analisis()

        elif op == '2':
            print("\nNodos disponibles:")
            for i, n in enumerate(NODOS, 1):
                print(f"  {i:2d}. {n}")
            sel = input("Seleccione numero: ").strip()
            try:
                nombre = NODOS[int(sel) - 1]
                ejecutar_analisis(nodos=[nombre])
            except (IndexError, ValueError):
                print("Seleccion no valida.")

        elif op == '3':
            print(f"\n{'='*65}")
            print(f"  {'Nodo':<20} | {'Mejor':>5} | {'PM3':>7} | {'SES':>7} | {'Holt':>7} | {'HW':>7}")
            print(f"  {'-'*20}-+-{'-'*5}-+-{'-'*7}-+-{'-'*7}-+-{'-'*7}-+-{'-'*7}")
            for nombre in NODOS:
                if nombre in demanda_historica:
                    mejor, errores = seleccionar_metodo(demanda_historica[nombre])
                    fila = f"  {nombre:<20} | {mejor:>5} |"
                    for m in ['PM3', 'SES', 'Holt', 'HW']:
                        e = errores.get(m, float('inf'))
                        marca = '*' if m == mejor else ' '
                        fila += f" {e:6.1f}{marca} |"
                    print(fila)

        elif op == '4':
            print("\nCalculando todos los nodos...")
            res = ejecutar_analisis(verbose=False)
            exportar_excel(res)

        elif op == '5':
            print("Saliendo...")
            break

        else:
            print("Opcion no valida.")


if __name__ == "__main__":
    menu()