# -*- coding: utf-8 -*-
"""lawer 0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wWPCPu0VvdXF98dMDWF9YFO9CkKeIDN
"""

# =============================================================
# Algoritmo de Lawler para minimizar el retardo máximo (T_max)
# en una máquina única con restricciones de precedencia
# =============================================================

import matplotlib.pyplot as plt # Importar al inicio del notebook

def plot_gantt(schedule):
    """Genera un diagrama de Gantt para la secuencia dada."""
    fig, ax = plt.subplots()
    start_time = 0
    for job in schedule:
        ax.barh(y=0, width=job['processing_time'], left=start_time, label=f"Job {job['id']}")
        start_time += job['processing_time']
    ax.set_xlabel("Tiempo")
    ax.set_title("Diagrama de Gantt")
    plt.show()

def lawler_algorithm(jobs, precedences):
    """
    Implementación del algoritmo de Lawler para secuenciar trabajos en una máquina
    con precedencias, minimizando el retardo máximo (T_max).

    Args:
        jobs (list): Lista de diccionarios con 'id', 'due_date' y 'processing_time'.
        precedences (list): Lista de tuplas (i, j) donde el trabajo i precede al j.

    Returns:
        tuple: (secuencia_optima, T_max, matriz_de_tardanzas)
    """
    # Inicializar estructuras de datos
    n = len(jobs)
    remaining_jobs = jobs.copy()
    schedule = []  # Almacenará la secuencia óptima
    successors = {job['id']: [] for job in jobs}  # Sucesores de cada trabajo

    # Construir el diccionario de sucesores a partir de las precedencias
    for i, j in precedences:
        successors[i].append(j)

    # Algoritmo de secuenciación hacia atrás
    for _ in range(n):
        # 1. Identificar trabajos candidatos (sin sucesores pendientes)
        candidates = [
            job for job in remaining_jobs
            if all(succ not in [j['id'] for j in remaining_jobs] for succ in successors[job['id']])
        ]

        # 2. Seleccionar el trabajo con la menor fecha de entrega (d_j)
        selected_job = min(candidates, key=lambda x: x['due_date'])

        # 3. Añadir al inicio de la secuencia (programación hacia atrás)
        schedule.insert(0, selected_job)
        remaining_jobs.remove(selected_job)

    # Calcular tiempos de finalización y tardanzas
    completion_time = 0
    T_max = 0
    tardiness = {}

    for job in schedule:
        completion_time += job['processing_time']
        T_j = max(0, completion_time - job['due_date'])
        tardiness[job['id']] = T_j
        if T_j > T_max:
            T_max = T_j

    return schedule, T_max, tardiness

# =============================================================
# Datos del Problema 3 (Tabla 3)
# =============================================================
jobs = [
    {'id': 1, 'due_date': 8, 'processing_time': 15},
    {'id': 2, 'due_date': 4, 'processing_time': 14},
    {'id': 3, 'due_date': 7, 'processing_time': 15},
    {'id': 4, 'due_date': 5, 'processing_time': 4},
    {'id': 5, 'due_date': 15, 'processing_time': 13},
    {'id': 6, 'due_date': 12, 'processing_time': 8},
    {'id': 7, 'due_date': 3, 'processing_time': 16},
    {'id': 8, 'due_date': 7, 'processing_time': 8},
    {'id': 9, 'due_date': 15, 'processing_time': 12},
    {'id': 10, 'due_date': 6, 'processing_time': 5},
    {'id': 11, 'due_date': 9, 'processing_time': 14},
    {'id': 12, 'due_date': 17, 'processing_time': 12},
    {'id': 13, 'due_date': 14, 'processing_time': 16},
    {'id': 14, 'due_date': 5, 'processing_time': 6},
    {'id': 15, 'due_date': 20, 'processing_time': 4},
    {'id': 16, 'due_date': 14, 'processing_time': 16},
    {'id': 17, 'due_date': 8, 'processing_time': 8},
    {'id': 18, 'due_date': 16, 'processing_time': 11},
    {'id': 19, 'due_date': 16, 'processing_time': 3},
]

# =============================================================
# Ejemplo de restricciones de precedencia (ajustar según Figura 1)
# NOTA: Reemplazar con las pre(17, 16),   # El trabajo 1 debe preceder al 3cedencias reales del problema.
# =============================================================
precedences = [
    (17, 16),   # El trabajo 17 debe preceder al 16
    (17, 6),   # El trabajo 17 debe preceder al 6
    (6, 1),   # El trabajo 1 debe preceder al 3
    (6, 2),   # El trabajo 1 debe preceder al 3
    (18, 16),   # El trabajo 18 debe preceder al 6
    (19, 16),   # El trabajo 1 debe preceder al 3
    (19, 8),   # El trabajo 1 debe preceder al 3
    (16, 14),   # El trabajo 1 debe preceder al 3
    (16, 15),   # El trabajo 1 debe preceder al 3
    (14, 13),   # El trabajo 1 debe preceder al 3
    (15, 13),   # El trabajo 1 debe preceder al 3
    (13, 10),   # El trabajo 1 debe preceder al 3
    (13, 11),   # El trabajo 1 debe preceder al 3
    (13, 12),   # El trabajo 1 debe preceder al 3
    (11, 9),   # El trabajo 1 debe preceder al 3
    (12, 9),   # El trabajo 1 debe preceder al 3
    (12, 8),   # El trabajo 1 debe preceder al 3
    (10, 9),   # El trabajo 1 debe preceder al 3
    (9, 7),   # El trabajo 1 debe preceder al 3
    (7, 2),   # El trabajo 1 debe preceder al 3
    (7, 3),   # El trabajo 1 debe preceder al 3
    (8, 4),   # El trabajo 1 debe preceder al 3

]
# =============================================================
# Ejecutar el algoritmo y mostrar resultados
# =============================================================
optimal_schedule, T_max, tardiness = lawler_algorithm(jobs, precedences)

# Imprimir resultados
print("Secuencia óptima:")
for job in optimal_schedule:
    print(f"Trabajo {job['id']} (d={job['due_date']}, p={job['processing_time']})")

print("\nTardanzas por trabajo:")
for job_id, T_j in tardiness.items():
    print(f"Trabajo {job_id}: Tardanza = {T_j}")

print(f"\nRetardo máximo (T_max): {T_max}")

# =============================================================
# Generar diagrama de Gantt (opcional, requiere matplotlib)
# =============================================================
# Importar librerías si es necesario:
# import matplotlib.pyplot as plt