# -*- coding: utf-8 -*-
"""Modelo pl punto 3 pcp tll1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPiWZvl2WaUKRYcqlFlPf2VdG8lerx9x
"""

!pip install pulp
!apt-get install -y coinor-cbc

from pulp import *

# Datos (ajustar según Tabla 3)
p = {
    1:15, 2:14, 3:15, 4:4, 5:13, 6:8, 7:16, 8:8, 9:12,
    10:5, 11:14, 12:12, 13:16, 14:6, 15:4, 16:16, 17:8, 18:11, 19:3
}

d = {
    1:8, 2:4, 3:7, 4:5, 5:15, 6:12, 7:3, 8:7, 9:15,
    10:6, 11:9, 12:17, 13:14, 14:5, 15:20, 16:14, 17:8, 18:16, 19:16
}

precedencias = precedencias = [(17,6 ), (17, 16), (18, 16), (19, 16),(19,8),(16,14),(16,15),(13,10),(13,11),(13,12),(10,9),(11,9),(12,9),(12,8),(9,7),(7,2),(7,3),(8,2),(8,4),(6,1),(6,2)]
M = sum(p.values())  # Constante grande
jobs = list(p.keys())

# Modelo
model = LpProblem("Min_Trabajos_Tardios", LpMinimize)

# Variables
C = LpVariable.dicts("C", jobs, lowBound=0)
u = LpVariable.dicts("u", jobs, cat='Binary')  # 1 si el trabajo j es tardío
x = LpVariable.dicts("x", [(i,j) for i in jobs for j in jobs if i != j], cat='Binary')

# Función Objetivo: Minimizar la cantidad de trabajos tardíos
model += lpSum(u[j] for j in jobs)

# Restricciones
for (i,j) in precedencias:
    model += C[i] + p[j] <= C[j]

for i in jobs:
    for j in jobs:
        if i != j and (i,j) not in precedencias and (j,i) not in precedencias:
            model += C[i] <= C[j] - p[j] + M*(1 - x[(i,j)])
            model += C[j] <= C[i] - p[i] + M*x[(i,j)]

for j in jobs:
    model += C[j] >= p[j]  # Tiempo mínimo de finalización
    model += C[j] - d[j] <= M * u[j]  # Vincula u_j con el retardo

# Resolver con COIN-OR (más rápido que el solver por defecto)
solver = COIN_CMD(msg=True, timeLimit=350)
model.solve(solver)

# Resultados
print("Estado:", LpStatus[model.status])
if model.status == 1:
    print("Trabajos tardíos:", sum(value(u[j]) for j in jobs))
    print("Detalles:")
    for j in jobs:
        print(f"Trabajo {j}: C={value(C[j]):.1f}, u={value(u[j])}")
else:
    print("Modelo infactible. Revisar precedencias o datos.")