# -*- coding: utf-8 -*-
"""Precedencias ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OdWA7te3PxMB7L2irAEn54JCxfeLNFA
"""

#inciso 3 para precedencias
import matplotlib.pyplot as plt
import heapq
from collections import defaultdict

# === Datos ===
jobs_data = {
    'A': {'p': 5,  'd': 10, 'w1': 2, 'w2': 4,'speeds': [2,3]},
    'B': {'p': 3,  'd': 11, 'w1': 4, 'w2': 2,'speeds': [1,2]},
    'C': {'p': 6,  'd': 6,  'w1': 5, 'w2': 3,'speeds': [2,3]},
    'D': {'p': 8,  'd': 5,  'w1': 1, 'w2': 6,'speeds': [2,3]},
    'E': {'p': 10, 'd': 8,  'w1': 9, 'w2': 8,'speeds': [2,3]},
    'F': {'p': 7,  'd': 4,  'w1': 5, 'w2': 6,'speeds': [2,3]},
    'G': {'p': 1,  'd': 8,  'w1': 1, 'w2': 3,'speeds': [2.5,3]},
    'H': {'p': 5,  'd': 10, 'w1': 2, 'w2': 2,'speeds': [1,3]},
    'I': {'p': 3,  'd': 12, 'w1': 7, 'w2': 4,'speeds': [1.5,2.5]}
}

precedence = [
    ('A', 'C'), ('A', 'D'), ('B', 'D'),
    ('C', 'F'), ('D', 'E'), ('D', 'F'),
    ('E', 'G'), ('F', 'G'), ('G', 'H'), ('G', 'I')
]

rules = {
    'SPT': lambda j: jobs_data[j]['p'],
    'LPT': lambda j: -jobs_data[j]['p'],
    'EDD': lambda j: jobs_data[j]['d'],
    'LDD': lambda j: -(jobs_data[j]['w2'] / jobs_data[j]['d'])
}

def build_graph(precedence):
    graph = defaultdict(list)
    in_degree = defaultdict(int)
    for a, b in precedence:
        graph[a].append(b)
        in_degree[b] += 1
    return graph, in_degree

def schedule_jobs(rule_name):
    graph, in_degree = build_graph(precedence)
    jobs = set(jobs_data.keys())
    ready = [j for j in jobs if in_degree[j] == 0]
    heap = [(rules[rule_name](j), j) for j in ready]
    heapq.heapify(heap)

    num_machines = len(next(iter(jobs_data.values()))['speeds'])
    machine_schedules = [[] for _ in range(num_machines)]
    job_times = {}
    gantt_data = []

    while heap:
        _, job = heapq.heappop(heap)
        preds = [pred for pred in jobs if job in graph[pred]]
        ready_time = max([job_times.get(p, 0) for p in preds], default=0)

        best_option = (float('inf'), float('inf'), None)

        for i in range(num_machines):
            speed = jobs_data[job]['speeds'][i]
            duration = jobs_data[job]['p'] / speed
            timeline = machine_schedules[i]

            available_time = ready_time
            for start, end in timeline:
                if available_time + duration <= start:
                    break
                available_time = max(available_time, end)
            end_time = available_time + duration

            if end_time < best_option[0]:
                best_option = (end_time, available_time, i)

        end, start, machine = best_option
        job_times[job] = end
        machine_schedules[machine].append((start, end))
        machine_schedules[machine].sort()
        gantt_data.append((machine, job, start, end - start))

        for succ in graph[job]:
            in_degree[succ] -= 1
            if in_degree[succ] == 0:
                heapq.heappush(heap, (rules[rule_name](succ), succ))

    return job_times, gantt_data

def evaluate(job_times):
    cmax = max(job_times.values())
    avg_cj = sum(job_times.values()) / len(job_times)
    cost = 0
    for job, c in job_times.items():
        d = jobs_data[job]['d']
        e = max(0, d - c)
        t = max(0, c - d)
        cost += jobs_data[job]['w1'] * e + jobs_data[job]['w2'] * t
    return cmax, avg_cj, cost

def plot_gantt(gantt_data, rule_name):
    fig, ax = plt.subplots(figsize=(10, 4))
    colors = plt.cm.tab20.colors
    color_map = {}
    for machine, job, start, duration in gantt_data:
        if job not in color_map:
            color_map[job] = colors[len(color_map) % len(colors)]
        ax.barh(machine, duration, left=start, color=color_map[job], edgecolor='black')
        ax.text(start + duration/2, machine, job, ha='center', va='center', color='white', fontsize=9)
    ax.set_yticks(range(len(set(m for m, _, _, _ in gantt_data))))
    ax.set_yticklabels([f'Máquina {i+1}' for i in range(len(set(m for m, _, _, _ in gantt_data)))])
    ax.set_xlabel("Tiempo")
    ax.set_title(f"Gantt - Regla {rule_name}")
    plt.grid(True, axis='x')
    plt.tight_layout()
    plt.show()

# === Ejecutar todas las reglas ===
for rule in rules:
    print(f"\n📌 Regla: {rule}")
    job_times, gantt_data = schedule_jobs(rule)
    cmax, avg_cj, cost = evaluate(job_times)
    print(f"  🔹 Cmax: {round(cmax, 2)}")
    print(f"  🔹 Promedio Cj: {round(avg_cj, 2)}")
    print(f"  🔹 Costo total ponderado: {round(cost, 2)}")
    plot_gantt(gantt_data, rule)

#inciso 3 para sin precedencias

import matplotlib.pyplot as plt
import heapq
from collections import defaultdict

# === Datos ===
jobs_data = {
    'A': {'p': 5,  'd': 10, 'w1': 2, 'w2': 4,'speeds': [2,3]},
    'B': {'p': 3,  'd': 11, 'w1': 4, 'w2': 2,'speeds': [1,2]},
    'C': {'p': 6,  'd': 6,  'w1': 5, 'w2': 3,'speeds': [2,3]},
    'D': {'p': 8,  'd': 5,  'w1': 1, 'w2': 6,'speeds': [2,3]},
    'E': {'p': 10, 'd': 8,  'w1': 9, 'w2': 8,'speeds': [2,3]},
    'F': {'p': 7,  'd': 4,  'w1': 5, 'w2': 6,'speeds': [2,3]},
    'G': {'p': 1,  'd': 8,  'w1': 1, 'w2': 3,'speeds': [2.5,3]},
    'H': {'p': 5,  'd': 10, 'w1': 2, 'w2': 2,'speeds': [1,3]},
    'I': {'p': 3,  'd': 12, 'w1': 7, 'w2': 4,'speeds': [1.5,2.5]}
}

precedence = [

]

rules = {
    'SPT': lambda j: jobs_data[j]['p'],
    'LPT': lambda j: -jobs_data[j]['p'],
    'EDD': lambda j: jobs_data[j]['d'],
    'LDD': lambda j: -(jobs_data[j]['w2'] / jobs_data[j]['d'])
}

def build_graph(precedence):
    graph = defaultdict(list)
    in_degree = defaultdict(int)
    for a, b in precedence:
        graph[a].append(b)
        in_degree[b] += 1
    return graph, in_degree

def schedule_jobs(rule_name):
    graph, in_degree = build_graph(precedence)
    jobs = set(jobs_data.keys())
    ready = [j for j in jobs if in_degree[j] == 0]
    heap = [(rules[rule_name](j), j) for j in ready]
    heapq.heapify(heap)

    num_machines = len(next(iter(jobs_data.values()))['speeds'])
    machine_schedules = [[] for _ in range(num_machines)]
    job_times = {}
    gantt_data = []

    while heap:
        _, job = heapq.heappop(heap)
        preds = [pred for pred in jobs if job in graph[pred]]
        ready_time = max([job_times.get(p, 0) for p in preds], default=0)

        best_option = (float('inf'), float('inf'), None)

        for i in range(num_machines):
            speed = jobs_data[job]['speeds'][i]
            duration = jobs_data[job]['p'] / speed
            timeline = machine_schedules[i]

            available_time = ready_time
            for start, end in timeline:
                if available_time + duration <= start:
                    break
                available_time = max(available_time, end)
            end_time = available_time + duration

            if end_time < best_option[0]:
                best_option = (end_time, available_time, i)

        end, start, machine = best_option
        job_times[job] = end
        machine_schedules[machine].append((start, end))
        machine_schedules[machine].sort()
        gantt_data.append((machine, job, start, end - start))

        for succ in graph[job]:
            in_degree[succ] -= 1
            if in_degree[succ] == 0:
                heapq.heappush(heap, (rules[rule_name](succ), succ))

    return job_times, gantt_data

def evaluate(job_times):
    cmax = max(job_times.values())
    avg_cj = sum(job_times.values()) / len(job_times)
    cost = 0
    for job, c in job_times.items():
        d = jobs_data[job]['d']
        e = max(0, d - c)
        t = max(0, c - d)
        cost += jobs_data[job]['w1'] * e + jobs_data[job]['w2'] * t
    return cmax, avg_cj, cost

def plot_gantt(gantt_data, rule_name):
    fig, ax = plt.subplots(figsize=(10, 4))
    colors = plt.cm.tab20.colors
    color_map = {}
    for machine, job, start, duration in gantt_data:
        if job not in color_map:
            color_map[job] = colors[len(color_map) % len(colors)]
        ax.barh(machine, duration, left=start, color=color_map[job], edgecolor='black')
        ax.text(start + duration/2, machine, job, ha='center', va='center', color='white', fontsize=9)
    ax.set_yticks(range(len(set(m for m, _, _, _ in gantt_data))))
    ax.set_yticklabels([f'Máquina {i+1}' for i in range(len(set(m for m, _, _, _ in gantt_data)))])
    ax.set_xlabel("Tiempo")
    ax.set_title(f"Gantt - Regla {rule_name}")
    plt.grid(True, axis='x')
    plt.tight_layout()
    plt.show()

# === Ejecutar todas las reglas ===
for rule in rules:
    print(f"\n📌 Regla: {rule}")
    job_times, gantt_data = schedule_jobs(rule)
    cmax, avg_cj, cost = evaluate(job_times)
    print(f"  🔹 Cmax: {round(cmax, 2)}")
    print(f"  🔹 Promedio Cj: {round(avg_cj, 2)}")
    print(f"  🔹 Costo total ponderado: {round(cost, 2)}")
    plot_gantt(gantt_data, rule)