# -*- coding: utf-8 -*-
"""Procesamiento de blocking .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byxwJCTSbjJxMcykemUHCwupvC9opWdM
"""

# CELDA ÚNICA: resolver, imprimir secuencia y tiempos, y graficar Gantt con procesamiento vs blocking
!pip install pulp matplotlib --quiet

import itertools
from pulp import LpProblem, LpMinimize, LpVariable, lpSum, LpBinary, value, PULP_CBC_CMD, LpStatus
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import defaultdict, deque

# --------------------------
# Datos (editar si quieres)
# --------------------------
jobs = ['j1','j2','j3','j4','j5','j6']
machines = [1,2,3]

p = {
    ('j1',1): 16, ('j1',2): 11, ('j1',3): 19,
    ('j2',1): 3,  ('j2',2): 2,  ('j2',3): 4,
    ('j3',1): 15, ('j3',2): 14, ('j3',3): 12,
    ('j4',1): 16, ('j4',2): 15, ('j4',3): 10,
    ('j5',1): 4,  ('j5',2): 3,  ('j5',3): 5,
    ('j6',1): 18, ('j6',2): 15, ('j6',3): 21,
}

# --------------------------
# Parámetros / big-M
# --------------------------
M = sum(p.values()) + 100.0

# --------------------------
# Modelo (permutation flowshop con blocking)
# --------------------------
model = LpProblem("Flowshop_balance_downtimes", LpMinimize)

# Variables
s = {(j,m): LpVariable(f"s_{j}_m{m}", lowBound=0) for j in jobs for m in machines}
cproc = {(j,m): LpVariable(f"c_{j}_m{m}", lowBound=0) for j in jobs for m in machines}
r = {(j,m): LpVariable(f"r_{j}_m{m}", lowBound=0) for j in jobs for m in machines}
b = {(j,m): LpVariable(f"b_{j}_m{m}", lowBound=0) for j in jobs for m in machines}

# binary order variables for pairs (i<j)
order = {}
pairs = []
for i, j in itertools.combinations(jobs, 2):
    order[(i,j)] = LpVariable(f"ord_{i}_{j}", cat=LpBinary)
    pairs.append((i,j))

# makespan, busy, dow, t (max diff)
T = LpVariable("T", lowBound=0)
busy = {m: LpVariable(f"busy_m{m}", lowBound=0) for m in machines}
dow = {m: LpVariable(f"dow_m{m}", lowBound=0) for m in machines}
t = LpVariable("t", lowBound=0)

# --------------------------
# Restricciones
# --------------------------

# cproc = s + p
for j in jobs:
    for m in machines:
        model += cproc[(j,m)] == s[(j,m)] + p[(j,m)], f"cproc_def_{j}_m{m}"

# flujo del trabajo a través de las máquinas
for j in jobs:
    model += s[(j,2)] >= cproc[(j,1)], f"flow_{j}_1to2"
    model += s[(j,3)] >= cproc[(j,2)], f"flow_{j}_2to3"

    # release linking
    model += r[(j,1)] == s[(j,2)], f"release_link_{j}_1"
    model += r[(j,2)] == s[(j,3)], f"release_link_{j}_2"
    model += r[(j,3)] == cproc[(j,3)], f"release_link_{j}_3"

    # blocking defs
    for m in machines:
        model += b[(j,m)] >= r[(j,m)] - cproc[(j,m)], f"block_def_{j}_m{m}"
        model += b[(j,m)] >= 0, f"block_nonneg_{j}_m{m}"
        model += b[(j,m)] <= M, f"block_ub_{j}_m{m}"

# secuencia permutada: misma orden en todas las máquinas
for (i,j) in pairs:
    for m in machines:
        model += s[(j,m)] >= r[(i,m)] - M * (1 - order[(i,j)]), f"seq_{i}_{j}_m{m}_a"
        model += s[(i,m)] >= r[(j,m)] - M * order[(i,j)], f"seq_{i}_{j}_m{m}_b"

# makespan >= todos los releases en la última máquina
for j in jobs:
    model += T >= r[(j,3)], f"T_ge_r_last_{j}"

# busy y downtime por máquina
for m in machines:
    model += busy[m] == lpSum((r[(j,m)] - s[(j,m)]) for j in jobs), f"busy_def_m{m}"
    model += dow[m] == T - busy[m], f"dow_def_m{m}"
    model += dow[m] >= 0, f"dow_nonneg_m{m}"

# diferencia máxima de downtimes
for m1, m2 in itertools.combinations(machines, 2):
    model += dow[m1] - dow[m2] <= t, f"tdiff_pos_m{m1}_m{m2}"
    model += dow[m2] - dow[m1] <= t, f"tdiff_neg_m{m1}_m{m2}"

# objetivo: minimizar la diferencia máxima de downtimes
model += t, "Minimize_max_dow_difference"

# --------------------------
# Resolver
# --------------------------
solver = PULP_CBC_CMD(msg=1, timeLimit=120)
model.solve(solver)

print("Solver status:", LpStatus[model.status])
print("Objective t (max dow diff):", value(t))
print("Makespan T:", value(T))
print("---- Busy and Downtimes ----")
for m in machines:
    print(f"Machine {m}: busy = {value(busy[m]):.4f}, dow = {value(dow[m]):.4f}")

# --------------------------
# Reconstruir la secuencia
# --------------------------
adj = {j: set() for j in jobs}
in_deg = {j: 0 for j in jobs}
for (i,j) in pairs:
    val = value(order[(i,j)]) or 0
    if round(val) == 1:
        adj[i].add(j)
        in_deg[j] += 1
    else:
        adj[j].add(i)
        in_deg[i] += 1

q = deque([j for j in jobs if in_deg[j] == 0])
sequence = []
while q:
    u = q.popleft()
    sequence.append(u)
    for v in list(adj[u]):
        in_deg[v] -= 1
        if in_deg[v] == 0:
            q.append(v)

if len(sequence) != len(jobs):
    print("Warning: cycle detected in ordering.")
else:
    print("\nFinal sequence (first -> last):", " -> ".join(sequence))

# --------------------------
# Imprimir tiempos detallados
# --------------------------
print("\nDetailed timing per job per machine:")
print("job | machine | s | cproc | r (release) | blocking")
for j in jobs:
    for m in machines:
        s_val = value(s[(j,m)])
        c_val = value(cproc[(j,m)])
        r_val = value(r[(j,m)])
        b_val = value(b[(j,m)])
        print(f"{j:>3} |   {m}     | {s_val:7.3f} | {c_val:7.3f} | {r_val:7.3f} | {b_val:7.3f}")

# --------------------------
# Construcción del Gantt
# --------------------------
schedule_proc = []
schedule_block = []
for j in jobs:
    for m in machines:
        s_val = value(s[(j,m)])
        c_val = value(cproc[(j,m)])
        r_val = value(r[(j,m)])
        if None in (s_val, c_val, r_val):
            continue
        schedule_proc.append((m, j, float(s_val), float(c_val)))
        if float(r_val) - float(c_val) > 1e-6:
            schedule_block.append((m, j, float(c_val), float(r_val)))

schedule_proc.sort(key=lambda x: (x[0], x[2]))
schedule_block.sort(key=lambda x: (x[0], x[2]))

def plot_gantt(proc, block, title="Gantt: processing (solid) + blocking (hatched)"):
    if not proc:
        print("No processing intervals to plot.")
        return
    machines_sorted = sorted(set(m for m,_,_,_ in proc))
    y_pos = {m: idx for idx, m in enumerate(machines_sorted)}
    fig, ax = plt.subplots(figsize=(12, max(4, len(machines_sorted)*1.2)))
    colors = plt.cm.tab20.colors
    color_map = {}
    for (m, j, s_st, s_end) in proc:
        if j not in color_map:
            color_map[j] = colors[len(color_map) % len(colors)]
        ax.barh(y_pos[m], s_end - s_st, left=s_st, color=color_map[j], edgecolor="black", height=0.4)
        ax.text(s_st + (s_end - s_st)/2, y_pos[m], j, ha="center", va="center", color="white", fontsize=8)
    for (m, j, b_st, b_end) in block:
        if j not in color_map:
            color_map[j] = colors[len(color_map) % len(colors)]
        ax.barh(y_pos[m], b_end - b_st, left=b_st, color=color_map[j], edgecolor="black",
                height=0.15, hatch='////', alpha=0.9)
    ax.set_yticks([y_pos[m] for m in machines_sorted])
    ax.set_yticklabels([f"Máquina {m}" for m in machines_sorted])
    ax.set_xlabel("Tiempo")
    ax.set_title(title)
    ax.grid(True, axis="x", linestyle="--", alpha=0.5)
    legend_patches = [mpatches.Patch(color=color_map[j], label=j) for j in sorted(color_map.keys())]
    ax.legend(handles=legend_patches, bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

plot_gantt(schedule_proc, schedule_block, title=f"Gantt (t={value(t):.4f}, T={value(T):.2f})")

import graphviz
from IPython.display import display, HTML

# 1. Inicializar el grafo dirigido (flujo de materiales)
dot = graphviz.Digraph(
    comment='Diagrama de Materia Prima (PEBD)',
    graph_attr={'rankdir': 'TB', 'bgcolor': 'white', 'nodesep': '0.5', 'ranksep': '0.7'},
    node_attr={'style': 'filled', 'color': 'black', 'fontname': 'Arial', 'shape': 'box', 'fillcolor': '#D3EAF1'}
)

# 2. Definir los Nodos (Ingredientes y Pasos)
# Materias Primas principales (color blanco para diferenciar la materia base)
dot.node('A', 'PEBD (BD) Virgen', fillcolor='#FFFFFF')
dot.node('B', 'PEBD (BD) Reciclado', fillcolor='#FFFFFF')

# Aditivos (color amarillo suave para diferenciar aditivos/componentes menores)
dot.node('D', 'Colorantes (Pigmentos)', fillcolor='#FFFFCC')
dot.node('F', 'Aditivos Funcionales\n(Deslizantes, Antiestáticos)', fillcolor='#FFFFCC')

# Nodos de Proceso (Tolva, Extrusora)
dot.node('C', 'Mezcla Base de Polietileno BD')
dot.node('E', 'Tolva: Dosificación y Pre-Mezcla', fillcolor='#AEEEEE', shape='rect') # Usamos color claro para el proceso de dosificación
dot.node('G', 'Alimentación a la Extrusora', fillcolor='#90EE90', shape='rect') # Punto de salida al proceso principal

# 3. Definir las Conexiones (Flujo)
# Creación de la Mezcla Base
dot.edge('A', 'C', arrowhead='normal')
dot.edge('B', 'C', arrowhead='normal')

# Alimentación a la Tolva (Mezcla de todos los componentes)
dot.edge('C', 'E', arrowhead='normal')
dot.edge('D', 'E', arrowhead='normal')
dot.edge('F', 'E', arrowhead='normal')

# Salida al Proceso de Extrusión
dot.edge('E', 'G', arrowhead='normal', penwidth='2') # Flecha más gruesa para la salida principal

# 4. Renderizar y mostrar en Google Colab
# Usamos el motor 'dot' por defecto, que maneja bien las dimensiones y flujos verticales.
# El método .pipe() con format='png' y ._repr_svg_() es la mejor manera de mostrar en Colab.
try:
    display(dot)
except Exception as e:
    # Esto se puede usar si hay problemas de rendering, para mostrar la fuente DOT
    print("Error al mostrar el gráfico. Código DOT generado:")
    print(dot.source)