# -*- coding: utf-8 -*-
"""Programacion de trabajos usando pandas y plotly .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19H2SQFosxnQXWJn4ZXF4d1yRsGBQAX_-
"""

import heapq
import time
import pandas as pd
import plotly.express as px

times_data = {
    1:  [4, 2, 1],
    2:  [2, 1, 1],
    3:  [4, 6, 2],
    4:  [5, 3, 2],
    5:  [2, 3, 1],
    6:  [7, 5, 3],
    7:  [2, 1, 2],
    8:  [4, 3, 1],
    9:  [5, 4, 2],
    10: [4, 8, 3]
}

def calc_c(seq, data):
    if not seq:
        return 0, 0, 0
    c1, c2, c3 = 0, 0, 0
    for j in seq:
        c1 += data[j][0]
        c2 = max(c1, c2) + data[j][1]
        c3 = max(c2, c3) + data[j][2]
    return c1, c2, c3

def bound(seq, unsched, data, c_times):
    if not unsched:
        return c_times[2]
    c1, c2, c3 = c_times
    s1 = sum(data[j][0] for j in unsched)
    s2 = sum(data[j][1] for j in unsched)
    s3 = sum(data[j][2] for j in unsched)
    m23 = min((data[j][1] + data[j][2]) for j in unsched)
    m3 = min(data[j][2] for j in unsched)
    return max(c1 + s1 + m23, c2 + s2 + m3, c3 + s3)

def solve(data):
    jobs = set(data.keys())
    n = len(data)
    heap = []
    ub = float('inf')
    best = []

    for j in jobs:
        c_times = calc_c([j], data)
        b = bound([j], jobs - {j}, data, c_times)
        heapq.heappush(heap, (b, 1, [j]))

    while heap:
        b, l, seq = heapq.heappop(heap)
        if b >= ub:
            continue
        if l == n:
            ub = calc_c(seq, data)[2]
            best = seq
            continue

        unsched = jobs - set(seq)
        c_times = calc_c(seq, data)

        for j in unsched:
            n_seq = seq + [j]
            n_unsched = unsched - {j}
            p1, p2, p3 = data[j]
            c1 = c_times[0] + p1
            c2 = max(c1, c_times[1]) + p2
            c3 = max(c2, c_times[2]) + p3
            n_c = (c1, c2, c3)
            nb = bound(n_seq, n_unsched, data, n_c)
            if nb < ub:
                heapq.heappush(heap, (nb, l + 1, n_seq))

    return best, ub

def plot_gantt(seq, data, makespan):
    records = []
    m1_end, m2_end, m3_end = 0, 0, 0

    base_date = pd.Timestamp("2026-03-09 00:00:00")

    for j in seq:
        p1, p2, p3 = data[j]

        m1_start = m1_end
        m1_end = m1_start + p1

        m2_start = max(m1_end, m2_end)
        m2_end = m2_start + p2

        m3_start = max(m2_end, m3_end)
        m3_end = m3_start + p3

        records.append(dict(Trabajo=f"Trabajo {j}", Maquina="M1", Start=base_date + pd.Timedelta(hours=m1_start), Finish=base_date + pd.Timedelta(hours=m1_end)))
        records.append(dict(Trabajo=f"Trabajo {j}", Maquina="M2", Start=base_date + pd.Timedelta(hours=m2_start), Finish=base_date + pd.Timedelta(hours=m2_end)))
        records.append(dict(Trabajo=f"Trabajo {j}", Maquina="M3", Start=base_date + pd.Timedelta(hours=m3_start), Finish=base_date + pd.Timedelta(hours=m3_end)))

    df = pd.DataFrame(records)

    fig = px.timeline(df, x_start="Start", x_end="Finish", y="Maquina", color="Trabajo",
                      title=f"Diagrama de Gantt - Secuencia Óptima (Makespan: {makespan} horas)",
                      labels={"Maquina": "Máquina"})

    fig.update_yaxes(autorange="reversed")

    fig.update_layout(xaxis=dict(
        title='Horas',
        tickformat='%H',
        tick0=base_date,
        dtick=3600000 * 2
    ))

    fig.show()

if __name__ == "__main__":
    t_inicio = time.time()
    best_seq, makespan = solve(times_data)
    t_fin = time.time()

    print(f"Secuencia Óptima: {best_seq}")
    print(f"Makespan: {makespan} horas")
    print(f"Tiempo de ejecución: {t_fin - t_inicio:.4f} segundos")

    plot_gantt(best_seq, times_data, makespan)

import heapq
import time
import pandas as pd
import plotly.express as px
import graphviz

times_data = {
    1:  [4, 2, 1],
    2:  [2, 1, 1],
    3:  [4, 6, 2],
    4:  [5, 3, 2],
    5:  [2, 3, 1],
    6:  [7, 5, 3],
    7:  [2, 1, 2],
    8:  [4, 3, 1],
    9:  [5, 4, 2],
    10: [4, 8, 3]
}

def calc_c(seq, data):
    if not seq:
        return 0, 0, 0
    c1, c2, c3 = 0, 0, 0
    for j in seq:
        c1 += data[j][0]
        c2 = max(c1, c2) + data[j][1]
        c3 = max(c2, c3) + data[j][2]
    return c1, c2, c3

def bound(seq, unsched, data, c_times):
    if not unsched:
        return c_times[2]
    c1, c2, c3 = c_times
    s1 = sum(data[j][0] for j in unsched)
    s2 = sum(data[j][1] for j in unsched)
    s3 = sum(data[j][2] for j in unsched)
    m23 = min((data[j][1] + data[j][2]) for j in unsched)
    m3 = min(data[j][2] for j in unsched)
    return max(c1 + s1 + m23, c2 + s2 + m3, c3 + s3)

def solve_bb(data):
    jobs = set(data.keys())
    n = len(data)
    heap = []
    ub = float('inf')
    best = []
    nodes_info = {}
    edges_info = []
    nodes_info["Raiz"] = {"label": "Raíz", "status": "Raiz"}
    for j in jobs:
        c_times = calc_c([j], data)
        b = bound([j], jobs - {j}, data, c_times)
        seq_str = str([j])
        nodes_info[seq_str] = {"label": f"J{j}\nLB: {b}", "status": "En Cola"}
        edges_info.append(("Raiz", seq_str))
        heapq.heappush(heap, (b, 1, [j]))
    while heap:
        b, l, seq = heapq.heappop(heap)
        seq_str = str(seq)
        if b >= ub:
            if seq_str in nodes_info:
                nodes_info[seq_str]["status"] = "Podado"
            continue
        if seq_str in nodes_info:
            nodes_info[seq_str]["status"] = "Explorado"
        if l == n:
            makespan = calc_c(seq, data)[2]
            if makespan < ub:
                ub = makespan
                best = seq
                nodes_info[seq_str]["status"] = "Optimo"
            continue
        unsched = jobs - set(seq)
        c_times = calc_c(seq, data)
        for j in unsched:
            n_seq = seq + [j]
            n_seq_str = str(n_seq)
            n_unsched = unsched - {j}
            p1, p2, p3 = data[j]
            c1 = c_times[0] + p1
            c2 = max(c1, c_times[1]) + p2
            c3 = max(c2, c_times[2]) + p3
            n_c = (c1, c2, c3)
            nb = bound(n_seq, n_unsched, data, n_c)
            nodes_info[n_seq_str] = {"label": f"J{j}\nLB: {nb}", "status": "En Cola"}
            edges_info.append((seq_str, n_seq_str))
            if nb < ub:
                heapq.heappush(heap, (nb, l + 1, n_seq))
            else:
                nodes_info[n_seq_str]["status"] = "Podado"
    return best, ub, nodes_info, edges_info

def export_full_tree_pdf(nodes_info, edges_info, filename="Arbol_Branch_and_Bound"):
    dot = graphviz.Digraph(format='pdf')
    dot.attr(rankdir='TB')
    dot.attr('node', shape='box', style='filled,rounded', fontname='Helvetica', fontsize='10')
    colors = {"Raiz": "lightgray", "Optimo": "gold", "Explorado": "lightblue", "Podado": "salmon", "En Cola": "white"}
    for n_id, info in nodes_info.items():
        dot.node(n_id, info['label'], fillcolor=colors.get(info['status'], "white"))
    for u, v in edges_info:
        dot.edge(u, v)
    dot.render(filename, view=False)

def plot_gantt(seq, data, makespan):
    records = []
    m1_end, m2_end, m3_end = 0, 0, 0

    base_date = pd.Timestamp("2026-03-09 00:00:00")

    for j in seq:
        p1, p2, p3 = data[j]

        m1_start = m1_end
        m1_end = m1_start + p1

        m2_start = max(m1_end, m2_end)
        m2_end = m2_start + p2

        m3_start = max(m2_end, m3_end)
        m3_end = m3_start + p3

        records.append(dict(Trabajo=f"Trabajo {j}", Maquina="M1", Start=base_date + pd.Timedelta(hours=m1_start), Finish=base_date + pd.Timedelta(hours=m1_end)))
        records.append(dict(Trabajo=f"Trabajo {j}", Maquina="M2", Start=base_date + pd.Timedelta(hours=m2_start), Finish=base_date + pd.Timedelta(hours=m2_end)))
        records.append(dict(Trabajo=f"Trabajo {j}", Maquina="M3", Start=base_date + pd.Timedelta(hours=m3_start), Finish=base_date + pd.Timedelta(hours=m3_end)))

    df = pd.DataFrame(records)

    fig = px.timeline(df, x_start="Start", x_end="Finish", y="Maquina", color="Trabajo",
                      title=f"Diagrama de Gantt - Secuencia Óptima (Makespan: {makespan} horas)",
                      labels={"Maquina": "Máquina"})

    fig.update_yaxes(autorange="reversed")

    fig.update_layout(xaxis=dict(
        title='Horas',
        tickformat='%H',
        tick0=base_date,
        dtick=3600000 * 2
    ))

    fig.show()

if __name__ == "__main__":
    t_inicio = time.time()
    best_seq, makespan, nodes_info, edges_info = solve_bb(times_data)
    t_fin = time.time()
    print(f"Secuencia Óptima: {best_seq}")
    print(f"Makespan: {makespan} horas")
    export_full_tree_pdf(nodes_info, edges_info)
    plot_gantt(best_seq, times_data, makespan)