# -*- coding: utf-8 -*-
"""Programacion con secuencia por maquina usando matplot y modelado lp problem .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8g_gjvAtfmqpVvrLwkYy9NTlNvSgdFl
"""

# CELDA ÚNICA: resolver, imprimir secuencia y tiempos, y graficar Gantt por máquinas
!pip install pulp matplotlib --quiet

import itertools
from pulp import LpProblem, LpMinimize, LpVariable, lpSum, LpBinary, value, PULP_CBC_CMD, LpStatus
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import defaultdict, deque

# --------------------------
# Datos
# --------------------------
jobs = ['j1','j2','j3','j4','j5','j6']
machines = [1,2,3]

p = {
    ('j1',1): 16, ('j1',2): 11, ('j1',3): 19,
    ('j2',1): 3,  ('j2',2): 2,  ('j2',3): 4,
    ('j3',1): 15, ('j3',2): 14, ('j3',3): 12,
    ('j4',1): 16, ('j4',2): 15, ('j4',3): 10,
    ('j5',1): 4,  ('j5',2): 3,  ('j5',3): 5,
    ('j6',1): 18, ('j6',2): 15, ('j6',3): 21,
}

M = sum(p.values()) + 100.0

# --------------------------
# Modelo de optimización
# --------------------------
model = LpProblem("Flowshop_blocking_balance", LpMinimize)

s = {(j,m): LpVariable(f"s_{j}_m{m}", lowBound=0) for j in jobs for m in machines}
cproc = {(j,m): LpVariable(f"c_{j}_m{m}", lowBound=0) for j in jobs for m in machines}
r = {(j,m): LpVariable(f"r_{j}_m{m}", lowBound=0) for j in jobs for m in machines}
b = {(j,m): LpVariable(f"b_{j}_m{m}", lowBound=0) for j in jobs for m in machines}

order = {}
pairs = []
for i, j in itertools.combinations(jobs, 2):
    order[(i,j)] = LpVariable(f"ord_{i}_{j}", cat=LpBinary)
    pairs.append((i,j))

T = LpVariable("T", lowBound=0)
busy = {m: LpVariable(f"busy_m{m}", lowBound=0) for m in machines}
dow = {m: LpVariable(f"dow_m{m}", lowBound=0) for m in machines}
t = LpVariable("t", lowBound=0)

# --------------------------
# Restricciones
# --------------------------
for j in jobs:
    for m in machines:
        model += cproc[(j,m)] == s[(j,m)] + p[(j,m)]
    model += s[(j,2)] >= cproc[(j,1)]
    model += s[(j,3)] >= cproc[(j,2)]

    model += r[(j,1)] == s[(j,2)]
    model += r[(j,2)] == s[(j,3)]
    model += r[(j,3)] == cproc[(j,3)]

    for m in machines:
        model += b[(j,m)] >= r[(j,m)] - cproc[(j,m)]
        model += b[(j,m)] >= 0
        model += b[(j,m)] <= M

for (i,j) in pairs:
    for m in machines:
        model += s[(j,m)] >= r[(i,m)] - M*(1 - order[(i,j)])
        model += s[(i,m)] >= r[(j,m)] - M*order[(i,j)]

for j in jobs:
    model += T >= r[(j,3)]

for m in machines:
    model += busy[m] == lpSum((r[(j,m)] - s[(j,m)]) for j in jobs)
    model += dow[m] == T - busy[m]
    model += dow[m] >= 0

for m1, m2 in itertools.combinations(machines, 2):
    model += dow[m1] - dow[m2] <= t
    model += dow[m2] - dow[m1] <= t

model += t

# --------------------------
# Resolver
# --------------------------
solver = PULP_CBC_CMD(msg=0, timeLimit=120)
model.solve(solver)

print("Solver status:", LpStatus[model.status])
print("Objetivo t (max diferencia de inactividad):", value(t))
print("Makespan T:", value(T))
print("\n---- Ocupación / Inactividad ----")
for m in machines:
    print(f"Máquina {m}: busy={value(busy[m]):.3f}, downtime={value(dow[m]):.3f}")

# --------------------------
# Secuencia reconstruida
# --------------------------
adj = {j: set() for j in jobs}
in_deg = {j: 0 for j in jobs}
for (i,j) in pairs:
    if round(value(order[(i,j)]) or 0) == 1:
        adj[i].add(j)
        in_deg[j] += 1
    else:
        adj[j].add(i)
        in_deg[i] += 1

q = deque([j for j in jobs if in_deg[j] == 0])
sequence = []
while q:
    u = q.popleft()
    sequence.append(u)
    for v in list(adj[u]):
        in_deg[v] -= 1
        if in_deg[v] == 0:
            q.append(v)

print("\nSecuencia final:", " → ".join(sequence))

# --------------------------
# Gantt por MÁQUINAS
# --------------------------
schedule_proc = []
schedule_block = []
for j in jobs:
    for m in machines:
        s_val, c_val, r_val = value(s[(j,m)]), value(cproc[(j,m)]), value(r[(j,m)])
        if None in (s_val, c_val, r_val):
            continue
        schedule_proc.append((m, j, s_val, c_val))
        if r_val - c_val > 1e-6:
            schedule_block.append((m, j, c_val, r_val))

schedule_proc.sort(key=lambda x: (x[0], x[2]))
schedule_block.sort(key=lambda x: (x[0], x[2]))

def plot_gantt_machines(proc, block, title="Gantt por máquinas"):
    fig, ax = plt.subplots(figsize=(12, 6))
    colors = plt.cm.tab20.colors
    color_map = {j: colors[i % len(colors)] for i, j in enumerate(sorted(set(j for _,j,_,_ in proc)))}

    y_positions = {m: i for i, m in enumerate(sorted(set(m for m,_,_,_ in proc)))}

    for (m, j, start, end) in proc:
        ax.barh(y_positions[m], end-start, left=start, color=color_map[j], edgecolor="black", height=0.35)
        ax.text(start + (end-start)/2, y_positions[m], j, ha="center", va="center", color="white", fontsize=8)

    for (m, j, start, end) in block:
        ax.barh(y_positions[m], end-start, left=start, color=color_map[j], edgecolor="black",
                height=0.15, hatch='////', alpha=0.8)

    ax.set_yticks([y_positions[m] for m in sorted(y_positions)])
    ax.set_yticklabels([f"M{m}" for m in sorted(y_positions)])
    ax.set_xlabel("Tiempo")
    ax.set_title(title)
    ax.grid(axis="x", linestyle="--", alpha=0.5)
    legend_patches = [mpatches.Patch(color=color_map[j], label=j) for j in sorted(color_map)]
    ax.legend(handles=legend_patches, loc='upper right')
    plt.tight_layout()
    plt.show()

plot_gantt_machines(schedule_proc, schedule_block, title=f"Gantt por máquinas (T={value(T):.2f})")