# -*- coding: utf-8 -*-
"""Uso de reglas de secuenciacion con matplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1P4rf1T-W3Qvlfn9cT69teQzmOuu2ma
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import heapq
from collections import defaultdict

## Problema con Precedencias


# Datos
jobs_data = {
    'A': {'p': 5,  'd': 10, 'w1': 2, 'w2': 4,'speeds': [2,3]} ,
    'B': {'p': 3,  'd': 11, 'w1': 4, 'w2': 2,'speeds': [1,2]},
    'C': {'p': 6,  'd': 6,  'w1': 5, 'w2': 3,'speeds': [2,3]},
    'D': {'p': 8,  'd': 5,  'w1': 1, 'w2': 6,'speeds': [2,3]},
    'E': {'p': 10, 'd': 8,  'w1': 9, 'w2': 8,'speeds': [2,3]},
    'F': {'p': 7,  'd': 4,  'w1': 5, 'w2': 6,'speeds': [2,3]},
    'G': {'p': 1,  'd': 8,  'w1': 1, 'w2': 3,'speeds': [2.5,3]},
    'H': {'p': 5,  'd': 10, 'w1': 2, 'w2': 2,'speeds': [1,3]},
    'I': {'p': 3,  'd': 12, 'w1': 7, 'w2': 4,'speeds': [1.5,2.5]}
}

precedence = [
    ('A', 'C'), ('A', 'D'), ('B', 'D'),
    ('C', 'F'), ('D', 'E'), ('D', 'F'),
    ('E', 'G'), ('F', 'G'), ('G', 'H'), ('G', 'I')
]

# Reglas de prioridad
rules = {
    'SPT': lambda j: jobs_data[j]['p'],
    'LPT': lambda j: -jobs_data[j]['p'],
    'EDD': lambda j: jobs_data[j]['d'],
    'LDD': lambda j: - (jobs_data[j]['w2'] / jobs_data[j]['d'])
}


def build_graph(precedence):
    graph = defaultdict(list)
    in_degree = defaultdict(int)
    for a, b in precedence:
        graph[a].append(b)
        in_degree[b] += 1
    return graph, in_degree

def schedule_jobs(rule_name):
    graph, in_degree = build_graph(precedence)
    jobs = set(jobs_data.keys())
    ready = [j for j in jobs if in_degree[j] == 0]
    heap = [(rules[rule_name](j), j) for j in ready]
    heapq.heapify(heap)

    sample_job = next(iter(jobs_data.values()))
    num_machines = len(sample_job['speeds'])
    machine_times = [0.0 for _ in range(num_machines)]
    job_times = {}
    gantt_data = []

    # Almacenar intervalos ocupados por máquina para detectar huecos
    machine_intervals = {i: [] for i in range(num_machines)}

    while heap:
        _, job = heapq.heappop(heap)
        preds = [pred for pred in jobs if job in graph[pred]]
        ready_time = max([job_times.get(p, 0) for p in preds], default=0)

        best_machine = None
        best_start = float('inf')
        best_end = float('inf')

        for i in range(num_machines):
            speed = jobs_data[job]['speeds'][i]
            duration = jobs_data[job]['p'] / speed
            intervals = sorted(machine_intervals[i], key=lambda x: x[0])

            # Buscar huecos en la máquina i
            candidate_start = None
            current_end = 0
            for (start, end) in intervals:
                if current_end < start:
                    gap_start = max(current_end, ready_time)
                    gap_end = start
                    if gap_end - gap_start >= duration:
                        candidate_start = gap_start
                        break
                current_end = max(current_end, end)

            # Si no hay hueco, usar el final de la máquina
            if candidate_start is None:
                candidate_start = max(current_end, ready_time)

            candidate_end = candidate_start + duration
            if candidate_end < best_end:
                best_machine = i
                best_start = candidate_start
                best_end = candidate_end

        if best_machine is not None:
            machine_intervals[best_machine].append((best_start, best_end))
            machine_intervals[best_machine].sort(key=lambda x: x[0])
            job_times[job] = best_end
            gantt_data.append((best_machine, job, best_start, duration))

        # Liberar sucesores
        for succ in graph[job]:
            in_degree[succ] -= 1
            if in_degree[succ] == 0:
                heapq.heappush(heap, (rules[rule_name](succ), succ))

    return job_times, gantt_data


def evaluate(job_times):
    cmax = max(job_times.values())
    total_cj = sum(job_times.values())
    total_cost = 0
    for job, c in job_times.items():
        d = jobs_data[job]['d']
        e = max(0, d - c)
        t = max(0, c - d)
        total_cost += jobs_data[job]['w1'] * e + jobs_data[job]['w2'] * t
    return cmax, total_cj / len(job_times), total_cost

def plot_gantt(gantt_data, rule_name):
    fig, ax = plt.subplots(figsize=(10, 4))
    colors = plt.cm.tab20.colors
    color_map = {}

    # Obtener máquinas únicas usadas
    machines_used = sorted(set(machine for machine, _, _, _ in gantt_data))
    ax.set_yticks(machines_used)
    ax.set_yticklabels([f'Máquina {i+1}' for i in machines_used])  # Sin velocidad

    for entry in gantt_data:
        machine, job, start, duration = entry
        if job not in color_map:
            color_map[job] = colors[len(color_map) % len(colors)]
        ax.barh(machine, duration, left=start, color=color_map[job], edgecolor='black')
        ax.text(start + duration/2, machine, job, ha='center', va='center', color='white', fontsize=9)

    ax.set_xlabel('Tiempo')
    ax.set_title(f'Diagrama de Gantt - Regla {rule_name}')
    plt.grid(True, axis='x')
    plt.tight_layout()
    plt.show()

# Ejecutar para cada regla y graficar
for rule in rules.keys():
    job_times, gantt_data = schedule_jobs(rule)
    cmax, avg_cj, total_cost = evaluate(job_times)
    print(f"--- Regla: {rule} ---")
    print("Cmax:", round(cmax, 2))
    print("Promedio Cj:", round(avg_cj, 2))
    print("Costo ponderado:", round(total_cost, 2))
    plot_gantt(gantt_data, rule)