# -*- coding: utf-8 -*-
"""Uso didactico de graphviz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOi7cvWKHozroKfHT3rL6_0YJmAJUhV5
"""

# ✅ Paso 1: Instalar graphviz si no está instalado
!apt-get install graphviz -qq
!pip install graphviz --quiet

# ✅ Paso 2: Importar librería
from graphviz import Digraph

# ✅ Paso 3: Crear el diagrama de flujo
dot = Digraph(comment='Flujo de Materia Prima - Grassana', format='png')
dot.attr(rankdir='TB', size='10')

# Nodos con descripción detallada
etapas = {
    "1": "Recepción de materia prima\nGrasa de cerdo, res, , bufalo, gallina, cordero, cabra, pato, pescado",
    "2": "Inspección y selección\nControl de calidad e higiene",
    "3": "Almacenamiento en frío\n< 4 °C para conservación",
    "4": "Rendering (derretido)\nFundido a alta temperatura",
    "5": "Filtrado y purificación\nImpurezas, agua, sólidos",
    "6": "Refinado y formulación\nClarificación, mezclas cosméticas",
    "7": "Envasado\nFrascos de vidrio o PET alimenticio",
    "8": "Etiquetado y control final\nNormativa, lote, peso",
    "9": "Distribución\nE-commerce, tiendas, clientes"
}

# Agregar nodos
for key, label in etapas.items():
    dot.node(key, label, shape='doubleoctagon', style='filled', fillcolor='aquamarine')

# Conectar nodos
for i in range(1, len(etapas)):
    dot.edge(str(i), str(i+1))

# ✅ Paso 4: Mostrar el diagrama
dot.render('/content/flujo_grassana_detallado', view=True)
dot